GET http://172.18.0.2:8080/


### Needs authorization
GET http://172.18.0.2:8080/api/users
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjExODEzNjY3LCJleHAiOjE2MTE4MTM2ODd9.OEAx5fA_ZOBbcfaYAcsV-OkP5uZyHkx0LwGbbv7EU7U

###
POST http://172.18.0.2:8080/api/auth/login
Content-Type: application/json

{
    "email": "marcinemail@somepost.com",
    "password": "12345"
}

###
POST http://172.18.0.2:8080/api/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjExOTQ4NTQzLCJleHAiOjE2MTI0NzQxNDN9.T7ws9t5xk4_wd3WVkxHmlBkMhEeFkqa6WfK_TslVL8Q"
}