version: "3.7"
services:
  node:
    build: .
    working_dir: /home/node/app
    container_name: javascript_node
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/:/home/node/app
    expose:
      - "8080"
    ports: 
      - "8080:8080"  
    command: "npm start"